# Generated by Django 5.2.12 on 2026-03-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created DateTime"
            ),
        ),
    ]
