# Generated by Django 5.2.12 on 2026-03-31 05:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likecount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(default="Anonymous", max_length=14),
        ),
    ]
